name: py types

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
  workflow_dispatch:

jobs:
  mypy:
    name: mypy typehints check
    runs-on: 'ubuntu-latest'
    steps:
    - name: checkout software
      uses: actions/checkout@v2
      with:
        path: software
    - name: 'refresh install'
      run: |
        sudo apt-get update --fix-missing
    - name: 'install python3 mypy'
      run: |
        sudo apt-get install --fix-broken --ignore-missing mypy
    - name: 'show mypy directories'
      run: |
        find . -type d
        mypy --version
    - name: 'make type (mypy strict type checking)'
      id: check
      run: |
        make type -C software
